from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup

checkers_board = InlineKeyboardMarkup(inline_keyboard=[
[InlineKeyboardButton(text=' ', callback_data='whitecell_a1'),
    InlineKeyboardButton(text='⚫️', callback_data='blackcell_blackcheker_a2'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_a3'),
    InlineKeyboardButton(text='⚫️', callback_data='blackcell_blackcheker_a4'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_a5'),
    InlineKeyboardButton(text='⚫️', callback_data='blackcell_blackcheker_a6'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_a7'),
    InlineKeyboardButton(text='⚫️', callback_data='blackcell_blackcheker_a8')],
[InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_b1'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_b2'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_b3'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_b4'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_b5'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_b6'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_b7'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_b8')],
[InlineKeyboardButton(text=' ', callback_data='whitecell_c1'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_c2'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_c3'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_c4'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_c5'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_c6'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_c7'),
    InlineKeyboardButton(text='⚫', callback_data='blackcell_blackcheker_c8')],
[InlineKeyboardButton(text=' ', callback_data='blackcell_d1'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_d2'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_d3'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_d4'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_d5'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_d6'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_d7'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_d8')],
[InlineKeyboardButton(text=' ', callback_data='whitecell_e1'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_e2'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_e3'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_e4'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_e5'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_e6'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_e7'),
    InlineKeyboardButton(text=' ', callback_data='blackcell_e8')],
[InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_f1'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_f2'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_f3'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_f4'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_f5'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_f6'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_f7'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_f8')],
[InlineKeyboardButton(text=' ', callback_data='whitecell_g1'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_g2'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_g3'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_g4'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_g5'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_g6'),
    InlineKeyboardButton(text=' ', callback_data='whitecell_g7'),
    InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_g8')],
[InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_h1'),
InlineKeyboardButton(text=' ', callback_data='whitecell_h2'),
InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_h3'),
InlineKeyboardButton(text=' ', callback_data='whitecell_h4'),
InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_h5'),
InlineKeyboardButton(text=' ', callback_data='whitecell_h6'),
InlineKeyboardButton(text='⚪️', callback_data='blackcell_whitecheker_h7'),
InlineKeyboardButton(text=' ', callback_data='whitecell_h8')]
])