#from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardButton, InlineKeyboardMarkup
#
#peak_six = [KeyboardButton(text = '6♠️', callback_data = 'peak_six')]
#peak_seven = [KeyboardButton(text = '7♠️', callback_data = 'peak_seven')]
#peak_eight = [KeyboardButton(text = '8♠️', callback_data = 'peak_eight')]
#peak_nine = [KeyboardButton(text = '9♠️', callback_data = 'peak_nine')]
#peak_ten = [KeyboardButton(text = '10♠️', callback_data = 'peak_ten')]
#peak_jack = [KeyboardButton(text = 'J♠️', callback_data = 'peak_jack')]
#peak_queen = [KeyboardButton(text = 'Q♠️', callback_data = 'peak_queen')]
#peak_king = [KeyboardButton(text = 'K♠️', callback_data = 'peak_king')]
#peak_ace = [KeyboardButton(text = 'A♠️', callback_data = 'peak_ace')]
#
#cross_six = [KeyboardButton(text = '6♣️', callback_data = 'cross_six')]
#cross_seven = [KeyboardButton(text = '7♣️', callback_data = 'cross_seven')]
#cross_eight = [KeyboardButton(text = '8♣️', callback_data = 'cross_eight')]
#cross_nine = [KeyboardButton(text = '9♣️', callback_data = 'cross_nine')]
#cross_ten = [KeyboardButton(text = '10♣️', callback_data = 'cross_ten')]
#cross_jack = [KeyboardButton(text = 'J♣️', callback_data = 'cross_jack')]
#cross_queen = [KeyboardButton(text = 'Q♣️', callback_data = 'cross_queen')]
#cross_king = [KeyboardButton(text = 'K♣️', callback_data = 'cross_king')]
#cross_ace = [KeyboardButton(text = 'A♣️', callback_data = 'cross_ace')]
#
#chervil_six = [KeyboardButton(text = '6♥️', callback_data = 'chervil_six')]
#chervil_seven = [KeyboardButton(text = '7♥️', callback_data = 'chervil_seven')]
#chervil_eight = [KeyboardButton(text = '8♥️', callback_data = 'chervil_eight')]
#chervil_nine = [KeyboardButton(text = '9♥️', callback_data = 'chervil_nine')]
#chervil_ten = [KeyboardButton(text = '10♥️', callback_data = 'chervil_ten')]
#chervil_jack = [KeyboardButton(text = 'J♥️', callback_data = 'chervil_jack')]
#chervil_queen = [KeyboardButton(text = 'Q♥️', callback_data = 'chervil_queen')]
#chervil_king = [KeyboardButton(text = 'K♥️', callback_data = 'chervil_king')]
#chervil_ace = [KeyboardButton(text = 'A♥️', callback_data = 'chervil_ace')]
#
#tambourine_six = [KeyboardButton(text = '6♦️', callback_data = 'tambourine_six')]
#tambourine_seven = [KeyboardButton(text = '7♦️', callback_data = 'tambourine_seven')]
#tambourine_eight = [KeyboardButton(text = '8♦️', callback_data = 'tambourine_eight')]
#tambourine_nine = [KeyboardButton(text = '9♦️', callback_data = 'tambourine_nine️')]
#tambourine_ten = [KeyboardButton(text = '10♦️️', callback_data = 'tambourine_ten')]
#tambourine_jack = [KeyboardButton(text = 'J♦️', callback_data = 'tambourine_jack')]
#tambourine_queen = [KeyboardButton(text = 'Q♦️️', callback_data = 'tambourine_queen')]
#tambourine_king = [KeyboardButton(text = 'K♦️️', callback_data = 'tambourine_king️')]
#tambourine_ace = [KeyboardButton(text = 'A♦️', callback_data = 'tambourine_ace')]